### ISSUE TITLE
make: wayland-scanner: Command not found 

### ISSUE THREAD

**Issue by Anzal-calixto** [renesas-rz/demo-camera-image-overlay#1]
I am getting this error while trying to compile the demo-camera-overlay

this is the full error i am getting

`wayland-scanner code /opt/poky/3.1.14/sysroots/aarch64-poky-linux/usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml common/src/xdg-shell-protocol.c
make: wayland-scanner: Command not found
make: *** [Makefile:68: common/src/xdg-shell-protocol.c] Error 127`

**Comment by seebe** [comment]
To install wayland-scanner, run the command:

$ sudo apt-get install wayland-scanner

**Comment by Anzal-calixto** [comment]
it seems the package doesnt exist. does it has a different name 

i tried installing wayland-scanner++ but the error is same and now i tried installing libwayland-dev and make has sucessfully executed 

thanks for the help

**Comment by seebe** [comment]
>  and now i tried installing libwayland-dev and make has sucessfully executed

Oh, I think you are right.
That might be something we add to to the Readme.

The other way is to add these lines to your local.conf....

DISTRO_FEATURES_NATIVESDK_append = " wayland"
DISTRO_FEATURES_NATIVESDK_remove = " x11"

...but then you would have to rebuild Yocto and SDK.....and that takes too long.

Glad you got it working.

**Comment by seebe** [comment]
Added to FAQ section in Readme.md

**Comment by seebe** [comment]
Added to FAQ section in Readme.md
